name: 'DevSecOps CI/CD Pipeline'

on:
  push:
    branches: [ "dev-snky" ]
  pull_request:

permissions:
  contents: read

jobs:
  Terraform:
    name: 'Deployment and Staging'
    runs-on: ubuntu-latest
    needs: terraform-validate-plan
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
    
      - name: Terraform Apply
        working-directory: ./infrastructure 
        run: terraform apply tfplan.out   # Use the generated plan 
        env:
          TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID_STAGING }} # Credentials for staging env
          TF_VAR_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_STAGING }}