name: 'DevSecOps CI/CD Pipeline (Terraform Cloud)'

on:
  push:
    branches:
      - main
      - dev-snky
  pull_request:

permissions:
  contents: read

jobs:
  initialization:
    name: initialization
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }} # Notice indentation!

    env:            
      AWS_REGION: ${{ github.ref == 'refs/heads/main' && 'ap-southeast-1' || 'ap-northeast-1' }}
  
    defaults: 
      run:
        shell: bash

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Clear Terraform Cache 
      run: rm -rf .terraform 

  #install-dependencies:
  #  name: install-dependencies
  #  runs-on: ubuntu-latest
  #  needs: initialization
  #  steps:
  #    - name: Check out repository code
  #      uses: actions/checkout@v3
  #    - name: Install Snyk 
  #      run: npm install -g snyk
      # - name: Run Installation of Dependencies Commands
      #   run: npm install  

  # npm-audit:
  #  name: Scan and Fix Vulnerabilities with npm
  #  runs-on: ubuntu-latest
  #  needs: install-dependencies
  #  steps:
  #    - name: Check out repository code
  #      uses: actions/checkout@v3
  #    - name: Run npm audit fix
  #      run: npm audit fix
  #    - name: Run Scanning of Dependencies Commands
  #      run: npm audit
        
  terraform-check:
    name: pre-check with terraform
    runs-on: ubuntu-latest
    needs: initialization
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Terraform Init
        id: init
        env:
          AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_BUCKET_KEY_NAME: ${{ secrets.AWS_BUCKET_KEY_NAME }}
          AWS_REGION: ${{ github.ref == 'refs/heads/main' && 'ap-southeast-1' || 'ap-northeast-1' }}
        run: terraform init -backend-config="bucket=${AWS_BUCKET_NAME}" -backend-config="key=${AWS_BUCKET_KEY_NAME}" -backend-config="region=${AWS_REGION}"
      
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        continue-on-error: true
      
  synk-test:
    runs-on: ubuntu-latest
    needs: initialization
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install snyk
        run : npm install -g snyk
      - name: Run Snyk to check for vulnerabilities
        run: snyk iac test --severity-threshold=high 
        env:
          SNYK_TOKEN: '${{ secrets.SNYK_TOKEN }}'