name: Snyk Comprehensive Security scan

on:
  push:
    branches:
      - main
      - dev-snky
  pull_request:

jobs:
  SAST-SCA-IaC_Container_scan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Snyk CLI to check for security issues
        # Snyk can be used to break the build when it detects security issues.
        # In this case we want to upload the SAST issues to GitHub Code Scanning
        #uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb
        uses: snyk/actions/setup@v3
        env:
          # This is where you will need to introduce the Snyk API token created with your Snyk account
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

        # For Snyk Open Source you must first set up the development environment for your application's dependencies
        # For example for Node
        #- uses: actions/setup-node@v3
        #  with:
        #    node-version: 16
      - uses: actions/setup-node@v3
      - run: npm ci        

        # This authentication step is typically used before running security scans or other Snyk-related actions.
      - name: Snyk Auth
        run: snyk auth --debug ${{ secrets.SNYK_TOKEN }} 
        
        # Runs Snyk Code (SAST) analysis and uploads result into GitHub.
        # Report only vulnerabilities at the severity-threshold=high or higher
        # Use || true to not fail the pipeline
      - name: Snyk Code test(SAST)
        run: snyk code test --sarif --severity-threshold=high > snyk-code.sarif  || true

        # Runs Snyk Open Source (SCA) analysis and uploads result to Snyk.
        # Report only vulnerabilities at the severity-threshold=high or higher
      - name: Snyk Open Source test and monitor(SCA)
        run: |
          snyk test --all-projects --severity-threshold=high
          snyk monitor --all-projects --severity-threshold=high

        # Runs Snyk Infrastructure as Code (IaC) analysis and uploads result to Snyk.
        # Report only vulnerabilities at the severity-threshold=high or higher
        # Use || true to not fail the pipeline.
      - name: Snyk IaC test and report
        run: snyk iac test --report --severity-threshold=high  || true

        # Push the Snyk Code results into GitHub Code Scanning tab
      - name: Upload result to GitHub Code Scanning
        uses: github/jinnliong/scan
        with:
          sarif_file: snyk-code.sarif